services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: 'kirvideo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
